// Valores de estado de venta como strings planos (coinciden con los enums de
// Prisma SaleStatus/SaleSubStatus). NO importamos el cliente Prisma aquí porque
// este archivo lo consumen componentes de cliente, y eso arrastraría el runtime
// de Prisma al navegador.

export type SaleStatusValue =
  | 'EN_GESTION'
  | 'INGRESADA'
  | 'RECHAZADO'
  | 'NO_INGRESADA'
  | 'PENDIENTE_DE_INGRESO'
  | 'INSTALADA'
  | 'NO_INSTALADO'
  | 'PRE_RECHAZO'
  | 'OBSERVADO'
  | 'REINGRESADO'
  | 'REASIGNACION'
  | 'REMEDY'

/** Submotivo permitido por cada motivo. El backend valida esta pertenencia. */
export const SUBSTATUS_BY_STATUS: Record<string, string[]> = {
  EN_GESTION: ['SIN_INGRESO'],
  INGRESADA: [
    'PROGRAMADO', 'SIN_PROGRAMAR', 'SEGUIMIENTO', 'EN_EJECUCION',
    'PENDIENTE_DE_APROBACION_CREDITICIA', 'PENDIENTE_DE_EVALUACION_CREDITICIA',
    'AUDIO_OBSERVADO', 'PENDIENTE_DE_APROBACION_DE_AUDIO', 'PENDIENTE_DE_GRABACION',
    'PRE_RECHAZO', 'SIN_AGENDAMIENTO_EN_SISTEMA', 'REINGRESADO',
    'DERIVADO_A_PLANTA_EXTERNA', 'PENDIENTE_POR_AMPLIACION_DE_FAT',
    'EDIFICIO_SERA_CONSTRUIDO_CON_RED_FTTH',
  ],
  RECHAZADO: [
    'CLIENTE_CON_DEUDA', 'DIRECCION_CON_DEUDA', 'EDIFICIO_NO_LIBERADO',
    'INGRESADO_POR_OTRO_CANAL', 'SIN_INFRAESTRUCTURA_DE_RED', 'ZONA_PELIGROSA',
    'SERVICIO_SUSPENDIDO', 'CONTRATO_MOVISTAR', 'SOT_CON_ERRORES_DE_SISTEMAS',
    'NO_CUENTA_CON_SUMINISTRO_DE_LUZ', 'DUPLICIDAD', 'AUDIO_NO_CARGADO',
    'POR_MAL_INGRESO_DE_DIRECCION', 'POR_MALA_OFERTA',
    'SE_DERIVO_AL_BUZON_DE_ANALISIS_DE_RECHAZO',
  ],
  NO_INGRESADA: [
    'DATOS_INCORRECTOS', 'OFERTA_INVALIDA', 'FALTA_DE_CONTRATO_DE_VOZ',
    'RECHAZADO_POR_VALIDACION', 'NO_DESEA_PAGAR_RENTA_ADELANTADA',
    'NO_TIENE_DELIVERY_EN_LA_ZONA', 'MIGRACION_DE_PREPAGO_A_POSTPAGO',
    'NO_CALIFICA_A_ALTA_NUEVA', 'NO_CALIFICA_A_PORTABILIDAD',
    'INGRESADO_POR_OTRO_CANAL', 'PLANO_NO_HABILITADO', 'CLIENTE_INUBICABLE',
  ],
  PENDIENTE_DE_INGRESO: [
    'CONSULTA_PREVIA', 'NO_HAY_SISTEMA', 'DEUDA_EN_CLARO',
    'PENDIENTE_DE_APROBACION_CASO_PARAMETRO', 'DIRECCION_INCORRECTA',
    'PENDIENTE_DE_GENERAR_SOT', 'PENDIENTE_DE_DNI_CE',
    'SIN_FRANJA_DISPONIBLE_EN_CONSULTA', 'SE_ENVIO_DNI_A_SEGMENTOS',
    'CALL_PAGO_INSTALACION', 'CLIENTE_PAGO_INSTALACION', 'BLOQUEADO_POR_EQUIFAX',
    'PENDIENTE_DE_PAGO_DE_INST', 'PORTABILIDAD_DEUDA_EN_MOVISTAR',
    'SOLICITA_RENTA_ADELANTADA',
  ],
  INSTALADA: [
    'ATENDIDA', 'INSTALADO_POR_CERRAR', 'PENDIENTE_DE_PORTABILIDAD',
    'ATENDIDA_X_REASIGNACION', 'ATENDIDA_POR_EMPRESAS', 'ATENDIDA_X_CALL',
  ],
  NO_INSTALADO: ['CLIENTE_DESISTE', 'INGRESADO_POR_OTRO_CANAL', 'RETENCION_DE_MOVISTAR', 'OTRO'],
  PRE_RECHAZO: ['SE_MANDO_A_LEVANTAR_SOT', 'SEGUIMIENTO_POR_BACK_NO_CONTESTA'],
  OBSERVADO: [
    'REASIGNACION_EN_CONTRA', 'ATENDIDOS_POR_EMPRESAS', 'VERIFICANDO_RED_EN_LA_ZONA',
    'PENDIENTE_DE_REASIGNACION',
  ],
  REINGRESADO: ['A_SOLICITUD_DEL_CLIENTE', 'AUTOMATICO'],
  REASIGNACION: ['PENDIENTE_DE_ENVIAR', 'ENVIADO_A_REASIGNAR'],
  REMEDY: ['PENDIENTE_DE_INGRESO'],
}

export const SALE_STATUS_LABELS: Record<string, string> = {
  EN_GESTION: 'En gestión',
  INGRESADA: 'Ingresada',
  RECHAZADO: 'Rechazado',
  NO_INGRESADA: 'No ingresada',
  PENDIENTE_DE_INGRESO: 'Pendiente de ingreso',
  INSTALADA: 'Instalada',
  NO_INSTALADO: 'No instalado',
  PRE_RECHAZO: 'Pre-rechazo',
  OBSERVADO: 'Observado',
  REINGRESADO: 'Reingresado',
  REASIGNACION: 'Reasignación',
  REMEDY: 'Remedy',
}

export function subStatusLabel(sub: string): string {
  return sub.replace(/_/g, ' ')
}

export const SALE_STATUS_OPTIONS = Object.keys(SALE_STATUS_LABELS).map((s) => ({
  value: s,
  label: SALE_STATUS_LABELS[s],
}))

export function subStatusOptions(status: string) {
  return (SUBSTATUS_BY_STATUS[status] ?? []).map((s) => ({ value: s, label: subStatusLabel(s) }))
}
