-- Nuevos sub-estados negativos que faltaban en el enum de la BD.
ALTER TYPE "LEAD_SUBSTATUS" ADD VALUE IF NOT EXISTS 'YA_TIENE_CLARO';
ALTER TYPE "LEAD_SUBSTATUS" ADD VALUE IF NOT EXISTS 'NO_CALIFICA_POR_DNI';
